Repository TownyAdvanced/TownyCombat, pull requests merged in 2022-05, with the labels that each got.

#54 Added jump damage warning
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#55 Custom model data support
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
Labels: enhancement

#56 chore(README.md): fix typo
  README.md
Labels: documentation

#57 Misc Fixes & Improvements
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: bug, enhancement

#59 Add some Events
  src/main/java/io/github/townyadvanced/townycombat/events/TownyCombatSpecialCavalryHitEvent.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
Labels: enhancement
