Repository TownyAdvanced/TownyCombat, pull requests merged in 2022-04, with the labels that each got.

#8 Tactical Speed & Damage Adjustments
  LICENSE.md
  README.md
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
  src/main/java/io/github/townyadvanced/townycombat/commands/TownyCombatAdminCommand.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/JumpReductionTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: enhancement

#9 Cavalry encumbrance
  README.md
  src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/metadata/TownyCombatResidentMetaDataController.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/JumpReductionTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: enhancement

#10 Bow and crossbow encumbrance
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
Labels: enhancement

#11 Incoming Damage Reductions
  src/main/java/io/github/townyadvanced/townycombat/commands/TownyCombatAdminCommand.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
Labels: enhancement

#17 Add special chest weights
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
Labels: enhancement

#18 Cavalry Charges !
  src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatNationEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/JumpReductionTask.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: enhancement

#19 Charge Fix - go into cooldown on hit
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
Labels: bug

#24 Cav charge bugfix
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
Labels: bug

#22 Translate translatables through Towny's Translation.
  src/main/java/io/github/townyadvanced/townycombat/utils/Messaging.java
Labels: bug

#23 Improve the look of the ascii art.
  src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
Labels: enhancement

#28 Refactor Jump Stopper
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: bug, enhancement

#38 Misc Fixes and Improvements
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/metadata/TownyCombatResidentMetaDataController.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: bug, enhancement

#42 Cavalry Tanks!
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: enhancement

#43 Custom Spears and Warhammers
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
Labels: enhancement

#49 Stop horses getting stunned on damage
  README.md
  pom.xml
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
Labels: bug, enhancement

#50 Horse knockback resistance
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
  src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
  src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
  src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
Labels: bug, enhancement
